### ISSUE TITLE
autoconf-duckdns6.sh: 14: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by nex86** [gtwy/IPv6forDuckDNS#7] opened 2023-01-04 10:43 UTC
getting the following error when launching the script:
autoconf-duckdns6.sh: 14: Syntax error: redirection unexpected

running this from debian 11.

**Comment by gtwy** [comment] 2023-01-04 16:22
Do you have all of the prerequisites as listed in the README?

Line 14 directly references this
`read -r _ _ _ _ iface _ ipv4local <<<"$(ip r g 8.8.8.8 | head -1)"`

You should troubleshoot your system to see why that command doesn't work. I cannot reproduce it, so I am not sure what advice to give. Let me know what you find.

**Comment by gtwy** [comment] 2023-01-25 00:23
Closing this because I did not hear back. I will assume it was a dependency issue unless I hear something more from you.

**Closed as completed by gtwy** 2023-01-25 00:23 UTC
